[package]
name = "tailfany"
version = "0.1.0"
edition = "2024"
description = "Follow new data in all matching files, including files created later"
license = "MIT"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
globset = "0.4.20"
notify = "8.2.0"
same-file = "1.0.6"

[dev-dependencies]
tempfile = "3.27.0"
